version: '3'

services:
  bloomdbserver:
    image: postgres:13
    container_name: bloomdbserver
    ports:
      - '5123:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=testDB
    volumes:
      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/pg:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - pgnet
    restart: always

  pgadminFp:
    container_name: pgadmin_0121
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: /tmp/.pgadmin/servers.json
    volumes:
      - ./data/pgadmin:/tmp/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - pgnet
#    restart: unless-stopped

networks:
  pgnet:
    driver: bridge
